spring.application.name=e-commerce3

# H2 Database (se reinicia al parar la app)
# spring.datasource.url=jdbc:h2:mem:testdb
# spring.datasource.driverClassName=org.h2.Driver
# spring.datasource.username=sa
# spring.datasource.password=
# spring.h2.console.enabled=true
# spring.h2.console.path=/h2-console


# 1. Configuracion de la Fuente de Datos 
# Usa variables de entorno si están definidas (Docker), sino usa los valores por defecto (local)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/ecommerce_db3?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}

# 2. Driver especifico (Cuidado aqui: si usas MySQL, NO menciones a H2)
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# 3. JPA / Hibernate
# spring.jpa.hibernate.ddl-auto=update
# Esto borra la base en cada ejecución
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.defer-datasource-initialization=true

# JWT Configuration
# 1. Clave Secreta JWT (Secret Key)
# Esta clave se usa para firmar y validar el token. 
# Idealmente, use una variable de entorno en produccion.
# TODO: ssanchez - sacar la clave secreta de aqui en produccion, almacenarla en un lugar seguro como una variable de entorno del sistema Operativo
jwt.secret=miClaveSecretaDe32CaracteresParaJWT2025

# 2. Tiempo de Expiracion del Token (Expiration Time)
# Define por cuanto tiempo sera valido el token, en milisegundos (ms).
# Ejemplo: 24 horas = 86400000 ms
jwt.expiration=86400000